"""
Trimmed browser-safe subset of the reused project's src/config.py.

Generated by scripts/sync_src.py (Agent ENGINE, Phase 1) — do not hand-edit;
edit _TRIMMED_CONFIG in scripts/sync_src.py and re-run it instead.

The original src/config.py has import-time filesystem side effects
(os.makedirs of output directories computed relative to the repo root) that
make no sense once synced under docs/py/src/ (they would create directories
under docs/, outside Agent ENGINE's owned paths) and are pointless inside the
Pyodide virtual filesystem. CONTRACTS.md section 0 explicitly allows a "trimmed
browser-safe subset if needed". This file keeps ONLY the constants and
dataclasses the whitelisted detectors need, with the same values as the
original, and none of the path/os.makedirs code.
"""
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

# Signal-band constants (Hz) — verbatim values from the original src/config.py.
EHG_BAND_WIDE = (0.1, 3.0)          # full EHG content
EHG_BAND_CONTRACTION = (0.2, 1.2)   # clinically relevant contraction burst band
EHG_BAND_FW = (0.34, 1.0)           # "fast wave" band
TOCO_BAND = (0.0, 0.1)              # mechanical envelope is very slow

# Canonical analysis rate for cross-dataset comparison (Hz).
CANONICAL_FS = 20.0


@dataclass
class Interval:
    """A labelled contraction interval (or point) on a recording's time axis (seconds)."""
    onset: float
    offset: float
    ref_type: str
    peak: Optional[float] = None
    strength: Optional[float] = None
    strength_kind: Optional[str] = None
    label: str = "contraction"
    note: str = ""

    @property
    def duration(self) -> float:
        return max(0.0, self.offset - self.onset)


@dataclass
class Recording:
    """One continuous multichannel recording plus its ground-truth intervals."""
    rec_id: str
    dataset: str
    modality: str
    fs: float
    signals: "object"                 # np.ndarray (n_channels, n_samples)
    ch_names: list = field(default_factory=list)
    intervals: list = field(default_factory=list)
    dummies: list = field(default_factory=list)
    subject: str = ""
    aux: dict = field(default_factory=dict)
    meta: dict = field(default_factory=dict)

    @property
    def n_channels(self) -> int:
        return self.signals.shape[0]

    @property
    def n_samples(self) -> int:
        return self.signals.shape[1]

    @property
    def duration_s(self) -> float:
        return self.n_samples / self.fs
