#!/usr/bin/env python3
"""
sync_src.py — copy the *browser-safe* subset of the reused signal-processing
code into docs/py/src/ so Pyodide can import it, and emit docs/py/manifest.json
(the file list engine.js fetches into the Pyodide virtual filesystem).

Browser-safe = numpy/scipy only. We deliberately DO NOT copy the original
package __init__.py files (they pull in config/methods, some of which import
torch); instead we write empty __init__.py shims so `import src...` resolves to
just the whitelisted leaf modules.

Phase 0 scope: filters.py + features.py (enough for process() / extract_features()).
Phase 1 (Agent ENGINE) extends SAFE_MODULES with the DSP/physio detector modules
listed in docs/py/_whitelist.py, after confirming each is numpy/scipy-only.

Phase 1 note on config.py: the original src/config.py has import-time filesystem
side effects (os.makedirs of output dirs computed relative to the repo root —
harmless in the original repo, but meaningless/unwanted once synced under
docs/py/src/, where those relative paths land under docs/). CONTRACTS.md §0
explicitly anticipates this ("config.py (trimmed browser-safe subset if
needed)"). So config.py is NOT verbatim-copied via SAFE_MODULES; instead
`_write_trimmed_config()` below emits a trimmed docs/py/src/config.py with the
same constant VALUES and the same Interval/Recording dataclasses (verified by
Agent ENGINE's numeric self-test), minus the path/os.makedirs side effects.

Phase 1 note on pywt: `src.methods.dsp_freq.WaveletEnergyDetector.detect()`
does a RUNTIME `import pywt` (PyWavelets) — not a numpy/scipy dep, but pywt is
available natively and ships as a Pyodide package, so it's whitelisted (see
_whitelist.py). The manifest below records "pyodide_packages": ["pywt"] so
Phase 2 (engine.js) knows to `pyodide.loadPackage("pywt")` before any
run_detector("wavelet_energy", ...) call.

Owner: Agent DATA/ENGINE (Phase 1). This Phase-0 version is written by the
orchestrator to make the walking skeleton importable.
"""
from __future__ import annotations

import json
import os
import shutil

HERE = os.path.dirname(os.path.abspath(__file__))
WEB_ROOT = os.path.dirname(HERE)                                  # ehg-web/
SRC_ROOT = os.path.abspath(os.path.join(WEB_ROOT, "..",
                                        "uterine_contraction_detection", "src"))
PY_DIR = os.path.join(WEB_ROOT, "docs", "py")
DST_SRC = os.path.join(PY_DIR, "src")

# Modules copied verbatim from the reused project (paths relative to src/).
# Each MUST be numpy/scipy-only at import time (confirmed for all of these by
# Agent ENGINE, Phase 1 — see docs/py/_whitelist.py for per-module notes).
# NOTE: config.py is intentionally NOT in this list — see _write_trimmed_config().
SAFE_MODULES = [
    "preprocessing/filters.py",
    "features/features.py",
    "evaluation/metrics.py",       # DetectedEvent; sklearn import inside is lazy
                                    # and only reachable via evaluate(), never
                                    # called from web_engine.run_detector().
    "methods/base.py",             # BaseDetector, register, REGISTRY
    "methods/_dsp_common.py",      # shared DSP helpers (preprocess/fuse/threshold)
    "methods/physio_common.py",    # shared physio helpers
    "methods/baseline_rms.py",     # bandpass_rms
    "methods/dsp_energy.py",       # tkeo_energy, slope_hysteresis,
                                    # nonlinear_entropy, kalman_envelope
    "methods/dsp_freq.py",         # zcr_burst, wavelet_energy (needs pywt at run time)
    "methods/physio_spectral.py",  # physio_spectral
]

# Package dirs that need an (empty) __init__.py so imports resolve.
PACKAGE_DIRS = ["", "preprocessing", "features", "methods", "evaluation"]

# Extra py entrypoints already living in docs/py that the browser must load.
ENTRYPOINTS = ["web_engine.py", "_whitelist.py"]

# Extra (non-pypi-numpy/scipy) packages the Pyodide runtime must
# `pyodide.loadPackage(...)` before code that needs them can run. Recorded in
# manifest.json for Phase 2 (engine.js) to consume. Currently just pywt, needed
# only by the "wavelet_energy" detector's runtime `import pywt`.
PYODIDE_PACKAGES = ["pywt"]

# Trimmed, browser-safe subset of the reused src/config.py — see module
# docstring "Phase 1 note on config.py" above. Constant values and dataclass
# fields are kept IDENTICAL to the original; only the path/os.makedirs
# side-effecting code is dropped.
_TRIMMED_CONFIG = '''"""
Trimmed browser-safe subset of the reused project's src/config.py.

Generated by scripts/sync_src.py (Agent ENGINE, Phase 1) — do not hand-edit;
edit _TRIMMED_CONFIG in scripts/sync_src.py and re-run it instead.

The original src/config.py has import-time filesystem side effects
(os.makedirs of output directories computed relative to the repo root) that
make no sense once synced under docs/py/src/ (they would create directories
under docs/, outside Agent ENGINE's owned paths) and are pointless inside the
Pyodide virtual filesystem. CONTRACTS.md section 0 explicitly allows a "trimmed
browser-safe subset if needed". This file keeps ONLY the constants and
dataclasses the whitelisted detectors need, with the same values as the
original, and none of the path/os.makedirs code.
"""
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

# Signal-band constants (Hz) — verbatim values from the original src/config.py.
EHG_BAND_WIDE = (0.1, 3.0)          # full EHG content
EHG_BAND_CONTRACTION = (0.2, 1.2)   # clinically relevant contraction burst band
EHG_BAND_FW = (0.34, 1.0)           # "fast wave" band
TOCO_BAND = (0.0, 0.1)              # mechanical envelope is very slow

# Canonical analysis rate for cross-dataset comparison (Hz).
CANONICAL_FS = 20.0


@dataclass
class Interval:
    """A labelled contraction interval (or point) on a recording's time axis (seconds)."""
    onset: float
    offset: float
    ref_type: str
    peak: Optional[float] = None
    strength: Optional[float] = None
    strength_kind: Optional[str] = None
    label: str = "contraction"
    note: str = ""

    @property
    def duration(self) -> float:
        return max(0.0, self.offset - self.onset)


@dataclass
class Recording:
    """One continuous multichannel recording plus its ground-truth intervals."""
    rec_id: str
    dataset: str
    modality: str
    fs: float
    signals: "object"                 # np.ndarray (n_channels, n_samples)
    ch_names: list = field(default_factory=list)
    intervals: list = field(default_factory=list)
    dummies: list = field(default_factory=list)
    subject: str = ""
    aux: dict = field(default_factory=dict)
    meta: dict = field(default_factory=dict)

    @property
    def n_channels(self) -> int:
        return self.signals.shape[0]

    @property
    def n_samples(self) -> int:
        return self.signals.shape[1]

    @property
    def duration_s(self) -> float:
        return self.n_samples / self.fs
'''


def main() -> None:
    if not os.path.isdir(SRC_ROOT):
        raise SystemExit(f"reused src/ not found at {SRC_ROOT}")

    # Fresh copy of the synced tree.
    if os.path.isdir(DST_SRC):
        shutil.rmtree(DST_SRC)
    os.makedirs(DST_SRC, exist_ok=True)

    manifest_files: list[str] = list(ENTRYPOINTS)

    for pkg in PACKAGE_DIRS:
        pkg_dir = os.path.join(DST_SRC, pkg) if pkg else DST_SRC
        os.makedirs(pkg_dir, exist_ok=True)
        init_path = os.path.join(pkg_dir, "__init__.py")
        with open(init_path, "w") as fh:
            fh.write("# synced by scripts/sync_src.py — browser-safe shim\n")
        rel = os.path.join("src", pkg, "__init__.py") if pkg else os.path.join("src", "__init__.py")
        manifest_files.append(rel.replace(os.sep, "/"))

    for rel in SAFE_MODULES:
        src_file = os.path.join(SRC_ROOT, rel)
        if not os.path.isfile(src_file):
            raise SystemExit(f"safe module missing: {src_file}")
        dst_file = os.path.join(DST_SRC, rel)
        os.makedirs(os.path.dirname(dst_file), exist_ok=True)
        shutil.copyfile(src_file, dst_file)
        manifest_files.append(("src/" + rel).replace(os.sep, "/"))

    # config.py: trimmed browser-safe subset (generated, not copied — see
    # module docstring "Phase 1 note on config.py").
    if not os.path.isfile(os.path.join(SRC_ROOT, "config.py")):
        raise SystemExit(f"expected source config.py at {os.path.join(SRC_ROOT, 'config.py')}")
    config_dst = os.path.join(DST_SRC, "config.py")
    with open(config_dst, "w") as fh:
        fh.write(_TRIMMED_CONFIG)
    manifest_files.append("src/config.py")

    # Verify entrypoints exist (written by hand / earlier steps).
    for ep in ENTRYPOINTS:
        if not os.path.isfile(os.path.join(PY_DIR, ep)):
            raise SystemExit(f"entrypoint missing in docs/py: {ep}")

    manifest = {
        "schema": "ehg-pymanifest/1.0.0",
        "root": "py",                       # fetched relative to docs/ as py/<file>
        "sys_path": "/py",                  # mount point inside Pyodide FS
        "entry": "web_engine",              # module to import
        # Non-numpy/scipy Pyodide packages that must be pyodide.loadPackage()'d
        # before the corresponding detector can run. Phase 1 (Agent ENGINE)
        # finding: only "wavelet_energy" (src.methods.dsp_freq) needs this, via
        # its runtime `import pywt`. Phase 2 (engine.js) must load these lazily
        # (or at Engine.ready()) before calling Engine.runDetector for it.
        "pyodide_packages": PYODIDE_PACKAGES,
        "files": manifest_files,
    }
    manifest_path = os.path.join(PY_DIR, "manifest.json")
    with open(manifest_path, "w") as fh:
        json.dump(manifest, fh, indent=2)

    print(f"synced {len(SAFE_MODULES)} module(s) + 1 trimmed config.py + shims into {DST_SRC}")
    print(f"manifest -> {manifest_path} ({len(manifest_files)} files, "
          f"pyodide_packages={PYODIDE_PACKAGES})")


if __name__ == "__main__":
    main()
